/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    GuoduDrawer: typeof import('./src/components/guodu-drawer/guodu-drawer.vue')['default']
    GuoduDrawerHeader: typeof import('./src/components/guodu-drawer-header/guodu-drawer-header.vue')['default']
    GuoduEcharts: typeof import('./src/components/guodu-echarts/guodu-echarts.vue')['default']
    GuoduEmpty: typeof import('./src/components/guodu-empty/guodu-empty.vue')['default']
    GuoduGrid: typeof import('./src/components/guodu-grid/guodu-grid.vue')['default']
    GuoduList: typeof import('./src/components/guodu-list/guodu-list.vue')['default']
    GuoduListItem: typeof import('./src/components/guodu-list-item/guodu-list-item.vue')['default']
    GuoduLoading: typeof import('./src/components/guodu-loading/guodu-loading.vue')['default']
    GuoduNavBar: typeof import('./src/components/guodu-nav-bar/guodu-nav-bar.vue')['default']
    GuoduSeletor: typeof import('./src/components/guodu-seletor/guodu-seletor.vue')['default']
    GuoduTabs: typeof import('./src/components/guodu-tabs/guodu-tabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
