/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    GuoduCalendar: typeof import('./src/widgets/guodu-calendar/guodu-calendar.vue')['default']
    GuoduColorPicker: typeof import('./src/widgets/guodu-color-picker/guodu-color-picker.vue')['default']
    GuoduDrawer: typeof import('./src/widgets/guodu-drawer/guodu-drawer.vue')['default']
    GuoduDrawerHeader: typeof import('./src/widgets/guodu-drawer-header/guodu-drawer-header.vue')['default']
    GuoduEcharts: typeof import('./src/widgets/guodu-echarts/guodu-echarts.vue')['default']
    GuoduEmpty: typeof import('./src/widgets/guodu-empty/guodu-empty.vue')['default']
    GuoduLoading: typeof import('./src/widgets/guodu-loading/guodu-loading.vue')['default']
    GuoduModal: typeof import('./src/widgets/guodu-modal/guodu-modal.vue')['default']
    GuoduNavBar: typeof import('./src/widgets/guodu-nav-bar/guodu-nav-bar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShyLoadMore: typeof import('./src/components/shy-load-more/shy-load-more.vue')['default']
  }
}
